### ISSUE TITLE
"Add initital step" to new subject seems to be broken

### ISSUE THREAD

**Issue by oppl** [win-ce/VirtualEnactment#15]
at least when picking up an expected message

**Comment by oppl** [comment]
obviously caused by a null pointer exception:
`	at at.jku.ce.CoMPArE.elaborate.ElaborationUI.wizardCompleted(ElaborationUI.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:510)
	... 51 more
Caused by: java.lang.NullPointerException
	at at.jku.ce.CoMPArE.process.SendState.setSentMessage(SendState.java:35)
	at at.jku.ce.CoMPArE.elaborate.changeCommands.AddMessageToSendStateCommand.undo(AddMessageToSendStateCommand.java:30)
	at at.jku.ce.CoMPArE.elaborate.ProcessChangeTransaction.undo(ProcessChangeTransaction.java:67)
	at at.jku.ce.CoMPArE.visualize.VisualizeModelEvolution.<init>(VisualizeModelEvolution.java:30)
	at at.jku.ce.CoMPArE.CoMPArEUI.createHistorySlider(CoMPArEUI.java:229)
	at at.jku.ce.CoMPArE.CoMPArEUI.createBasicLayout(CoMPArEUI.java:136)
	at at.jku.ce.CoMPArE.CoMPArEUI.access$400(CoMPArEUI.java:45)
	at at.jku.ce.CoMPArE.CoMPArEUI$1.windowClose(CoMPArEUI.java:663)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:510)
	... 63 more

`
